// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB8_BzSyOfIDOYLydhoAjzFd4fzqdKbis',
    appId: '1:962853753155:web:25f1f80099d36d953c9ff6',
    messagingSenderId: '962853753155',
    projectId: 'flutterfirebase-fdb7d',
    authDomain: 'flutterfirebase-fdb7d.firebaseapp.com',
    storageBucket: 'flutterfirebase-fdb7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVmhwPi9xtAcfYoCaYYD86H-sTJHt4Qrs',
    appId: '1:962853753155:android:ad24a41d17ad1ade3c9ff6',
    messagingSenderId: '962853753155',
    projectId: 'flutterfirebase-fdb7d',
    storageBucket: 'flutterfirebase-fdb7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIN4J5BM_pdAEw0qpwVfdi6oIbC_17D64',
    appId: '1:962853753155:ios:f4c57e0f14c535493c9ff6',
    messagingSenderId: '962853753155',
    projectId: 'flutterfirebase-fdb7d',
    storageBucket: 'flutterfirebase-fdb7d.appspot.com',
    iosBundleId: 'com.example.flutterFirabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIN4J5BM_pdAEw0qpwVfdi6oIbC_17D64',
    appId: '1:962853753155:ios:e2045ec82d1472dc3c9ff6',
    messagingSenderId: '962853753155',
    projectId: 'flutterfirebase-fdb7d',
    storageBucket: 'flutterfirebase-fdb7d.appspot.com',
    iosBundleId: 'com.example.flutterFirabase.RunnerTests',
  );
}
